import React, { useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Upload, Sparkles, LayoutDashboard, WandSparkles, ChartNoAxesCombined, Route, Rocket, SlidersHorizontal, Check, CircleDollarSign, MousePointer2, Eye, Users, TrendingUp, Info, ArrowUpRight, Image as ImageIcon, RotateCw, ShieldCheck, Bell, Settings, Zap, MessageCircle, Plus, Bot, Library, CreditCard, LockKeyhole, X, Send, Layers3 } from 'lucide-react';
import './styles.css';

const channels = [
  { name:'TrafficJunky', model:'CPM', color:'#ff554f', base:24, note:'Tube inventory · keyword + geo' },
  { name:'ExoClick', model:'CPC / sCPM', color:'#ff806b', base:20, note:'Native + display · source rules' },
  { name:'JuicyAds', model:'CPC / CPM', color:'#ffad72', base:14, note:'Native + banner · device targeting' },
  { name:'Reddit', model:'Organic', color:'#e5c277', base:12, note:'Community-led discovery' },
  { name:'X / Social', model:'Organic', color:'#c3d661', base:11, note:'Preview-safe social funnel' },
  { name:'Creator swaps', model:'Flat fee', color:'#9fcf54', base:11, note:'Audience-aligned shoutouts' },
  { name:'SEO / Clips', model:'Owned', color:'#76bf52', base:8, note:'Compounding discovery' },
];

const nav = [
  [LayoutDashboard,'Overview'],[MessageCircle,'Chat Studio'],[ImageIcon,'Model Assets'],[WandSparkles,'Campaign Builder'],[ImageIcon,'Creatives'],[ChartNoAxesCombined,'Traffic Mix'],[Route,'Forecast'],[Rocket,'Launch Plan'],[Sparkles,'AI Skills'],[Zap,'Naughty Cheat Codes']
] as const;

const cheatCodes=[
  ['Website → Campaign','Turns approved public website language into a complete ad brief.'],['Angle Multiplier','Expands one photo into distinct premium, playful, direct, and curiosity angles.'],['Hook Miner','Finds short opening lines from the creator’s own brand language.'],['Source Matchmaker','Pairs each concept with the traffic source and format most likely to fit.'],['Safe-to-Spicy Ladder','Creates channel-appropriate intensity levels without changing brand voice.'],['CTA Switcher','Builds destination-specific calls to action for web, social, and subscriber pages.'],['Budget Splitter','Allocates the $300 test across selected sources and reserves retest spend.'],['Offer Mirror','Keeps the advertisement promise aligned with the destination page.'],['Retargeting Loop','Maps visitor, engaged-viewer, and checkout-return audiences.'],['Fatigue Radar','Flags repeated hooks and suggests the next creative rotation.'],['Compliance Shield','Checks age, consent, claim, and platform-policy risk before activation.'],['Upsell Architect','Maps future retention and add-on campaigns after the acquisition test.']
];

const skillCatalog=[
  ['Creator Growth Strategist','Funnel, acquisition, retention, and subscriber economics','ACTIVE'],['Adult Brand Positioning','Premium voice, messaging, offers, and normalized language','ACTIVE'],['Adult Traffic Buyer','TrafficJunky, ExoClick, JuicyAds, social, SEO, and partnerships','ACTIVE'],['Website Intelligence','Live business-site extraction and campaign grounding','ACTIVE'],['Creative Director','Ad angles, headlines, CTAs, formats, and variations','ACTIVE'],['Offer Optimizer','Pricing, promotion, landing promise, and conversion strategy','ACTIVE'],['Audience Architect','Geo, intent, lookalike, exclusion, and retargeting design','ACTIVE'],['Compliance Review','Consent, 18+, platform policy, claims, and creative checks','ACTIVE'],['Attribution Analyst','UTMs, source IDs, conversion events, CAC, and LTV','ACTIVE'],['Retention Engine','Renewal, churn reduction, upsell, and win-back campaigns','AVAILABLE'],['Landing Page Builder','Offer-matched conversion pages and age-gated flows','AVAILABLE'],['Cross-Platform Publisher','Channel-specific formatting, scheduling, and reporting','AVAILABLE']
];

function App(){
  const [budget,setBudget]=useState(300); const [price,setPrice]=useState(19.99); const [goal,setGoal]=useState(240);
  const [image,setImage]=useState<string>(); const [active,setActive]=useState('Overview'); const [generated,setGenerated]=useState(false); const [completed,setCompleted]=useState<number[]>([]); const [notice,setNotice]=useState(''); const [mixOpen,setMixOpen]=useState(false); const [building,setBuilding]=useState(false); const [demoStep,setDemoStep]=useState(0);
  const [creatorName,setCreatorName]=useState(''); const [socials,setSocials]=useState({x:'',instagram:'',reddit:'',tiktok:''});
  const [siteUrl,setSiteUrl]=useState(''); const [siteState,setSiteState]=useState<'idle'|'loading'|'done'|'error'>('idle'); const [siteData,setSiteData]=useState<any>();
  const [selectedAsset,setSelectedAsset]=useState<string>(); const [showBilling,setShowBilling]=useState(false);
  const input=useRef<HTMLInputElement>(null);
  const model=useMemo(()=>{
    const clicks=Math.round(budget/0.13); const visits=Math.round(clicks*.347); const baseline=Math.round(visits*.037*(price>25?.82:price<15?1.16:1));
    const mid=Math.max(1,baseline); return {clicks,visits,mid,low:Math.round(mid*.68),high:Math.round(mid*1.32),revenue:Math.round(mid*price)};
  },[budget,price]);
  const upload=(f?:File)=>{if(f){const r=new FileReader();r.onload=()=>{setImage(String(r.result));setBuilding(true);setNotice('Photo received. AI media buyer is building your campaign…');setTimeout(()=>{setBuilding(false);setGenerated(true);setNotice('AI campaign build complete — review every layer below.');},1400)};r.readAsDataURL(f)}};
  const build=()=>{setBuilding(true);setDemoStep(1);setNotice('AI is building the campaign with your latest inputs…');setTimeout(()=>{setBuilding(false);setGenerated(true);setDemoStep(6);setNotice('Campaign ready for review.');document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'})},1100)};
  const runDemo=()=>{if(building)return;setGenerated(false);setBuilding(true);setCompleted([]);setDemoStep(1);setNotice('AI is analyzing the creative…');const messages=['Analyzing creative direction','Selecting the conversion objective','Building the high-intent audience','Allocating the traffic mix','Generating nine ad variations','Campaign ready for review'];messages.forEach((message,index)=>setTimeout(()=>{setDemoStep(index+1);setNotice(message);if(index===messages.length-1){setBuilding(false);setGenerated(true);setCompleted([0,1,2,3]);setTimeout(()=>document.getElementById('results')?.scrollIntoView({behavior:'smooth',block:'start'}),300)}},650*(index+1)))};
  const analyzeWebsite=async()=>{if(!siteUrl.trim()){setNotice('Enter a business website first.');return}setSiteState('loading');setSiteData(undefined);try{const response=await fetch('/api/analyze-website',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:siteUrl})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Website analysis failed.');setSiteData(data);setSiteState('done');setNotice('Website analysis complete. Campaign profile and ad suggestions updated.')}catch(error){setSiteState('error');setNotice(error instanceof Error?error.message:'Website analysis failed.')}};
  const go=(name:string)=>{setActive(name);const ids:Record<string,string>={'Overview':'top','Campaign Builder':'builder','Creatives':'creatives','Traffic Mix':'mix','Forecast':'forecast','Launch Plan':'launch'};document.getElementById(ids[name])?.scrollIntoView({behavior:'smooth',block:'start'})};
  return <div className="app">
    <aside><div className="brand"><img src="/naughty-pilot-logo.png" alt="Naughty Pilot"/></div><nav>{nav.map(([I,n])=><button className={active===n?'on':''} onClick={()=>go(n)} key={n}><I/>{n}</button>)}</nav></aside>
    <main id="top">
      <header><div className="sim live"><i/> AI MEDIA BUYER <span>{building?'Campaign automation running':'Ready for your creative'}</span></div><div className="head-actions"><button onClick={()=>setNotice('No new account alerts.')}><Bell/></button><button onClick={()=>setNotice('Workspace preferences opened.')}><Settings/></button><div className="profile">NP <span><b>Naughty Pilot</b><small>Campaign workspace</small></span></div></div></header>
      {active==='Overview'?<>
      <section className="campaign-tabs"><button className="active"><span>1</span> Campaign</button><i/><button className={generated?'active':''}><span>2</span> Ad set</button><i/><button className={generated?'active':''}><span>3</span> Creatives</button></section>
      <section className="intro"><div className="home-copy"><img className="home-mark" src="/naughty-pilot-logo.png"/><div><h1>Drop your photos.<br/><em>AI builds the campaign.</em></h1><p>From one creative to a complete campaign—objective, audience, placements, budget, copy, ad variations, and forecast.</p><button className="ai-do" onClick={runDemo}><Sparkles/> {building?'AI IS WORKING…':'AI DO IT'}<ArrowUpRight/></button></div></div><div className="truth"><ShieldCheck/><div><b>AI build mode</b><span>Every campaign layer remains editable before launch.</span></div></div></section>
      <section id="builder" className="builder">
        <div className={'upload '+(building?'scanning':'')} onClick={()=>!building&&input.current?.click()}>{image?<img src={image}/>:<div className="placeholder"><Upload/><b>Drop campaign photo</b><span>JPG or PNG · AI analyzes the strongest angle</span><button>Choose photo</button></div>}{building&&<div className="scan"><Sparkles/><b>{['','Analyzing creative','Selecting objective','Building audience','Allocating placements','Generating ad suggestions','Campaign complete'][demoStep]}</b><span>AI campaign automation in progress</span><div className="progress"><i style={{width:`${Math.max(8,demoStep/6*100)}%`}}/></div></div>}<input ref={input} hidden type="file" accept="image/*" onChange={e=>upload(e.target.files?.[0])}/>{image&&!building&&<button className="replace">Replace photo</button>}</div>
        <div className="controls"><div className="ai-title"><Sparkles/><div><b>AI campaign setup</b><span>{generated?'Campaign generated · ready to edit':'Upload a photo to generate every layer'}</span></div></div><label>Campaign budget <b>${budget.toLocaleString()}</b></label><input type="range" min="100" max="10000" step="50" value={budget} onChange={e=>setBudget(+e.target.value)}/><div className="scale"><span>$100</span><span>$10k</span></div><label>Subscription price <b>${price.toFixed(2)}</b></label><input type="range" min="5" max="50" step="1" value={price} onChange={e=>setPrice(+e.target.value)}/><label>Subscriber target <b>{goal}+</b></label><input type="range" min="100" max="500" step="10" value={goal} onChange={e=>setGoal(+e.target.value)}/><div className="selects"><select><option>AI chooses best angle</option><option>Confident & playful</option><option>Luxury & exclusive</option><option>Girl-next-door</option></select><select><option>AI optimized · 21+</option><option>United States · 21+</option><option>US + Canada · 21+</option></select></div><button className="primary" disabled={building} onClick={build}><Sparkles/> {building?'Building campaign…':generated?'Rebuild with AI':'Build full campaign with AI'}</button></div>
      </section>
      {generated&&<div id="results"><section className="ai-output"><div><span>CAMPAIGN</span><b>Subscriber Growth · Conversions</b><small>Optimized for paid membership events</small></div><div><span>AUDIENCE</span><b>High-intent · US · 21+</b><small>Expanded interests and lookalike segments</small></div><div><span>PLACEMENTS</span><b>7-channel optimized mix</b><small>Automatic source-level allocation</small></div><div><span>CREATIVE</span><b>3 angles · 9 variations</b><small>Copy, crop, CTA, and format generated</small></div></section>
      <section id="forecast" className="forecast pulse"><div className="forecast-lead"><span>PROJECTED MIDPOINT</span><strong>{model.mid}</strong><b>paid subscribers</b><p>Planning range <em>{model.low}–{model.high}</em></p></div><div className="metrics"><Metric icon={CircleDollarSign} name="Test spend" value={'$'+budget.toLocaleString()}/><Metric icon={MousePointer2} name="Est. clicks" value={model.clicks.toLocaleString()}/><Metric icon={Eye} name="Landing visits" value={model.visits.toLocaleString()}/><Metric icon={Users} name="Paid conversions" value={model.mid.toLocaleString()}/><Metric icon={TrendingUp} name="Projected revenue" value={'$'+model.revenue.toLocaleString()}/><Metric icon={Info} name="Visit → paid" value={(model.mid/model.visits*100).toFixed(2)+'%'}/></div></section>
      <section id="mix" className="mix"><div className="section-title"><div><h2>Recommended traffic mix</h2><p>AI-optimized allocation based on the campaign objective and audience.</p></div><button onClick={()=>setMixOpen(!mixOpen)}><SlidersHorizontal/> {mixOpen?'Close mixer':'Adjust mix'}</button></div>{mixOpen&&<div className="mixer">{channels.map(c=><label key={c.name}><span>{c.name}</span><input type="range" min="0" max="40" defaultValue={c.base}/><b>{c.base}%</b></label>)}</div>}<div className="bar">{channels.map(c=><div style={{width:c.base+'%',background:c.color}} key={c.name}>{c.base}%</div>)}</div><div className="channel-grid">{channels.map(c=><button onClick={()=>setNotice(`${c.name} selected: ${c.note}.`)} key={c.name}><i style={{background:c.color}}/><b>{c.name}</b><span>{c.model}</span><small>${Math.round(budget*c.base/100)} · {c.note}</small></button>)}</div></section>
      <section className="lower"><div id="creatives" className="creative"><div className="section-title"><div><h2>AI ad suggestions</h2><p>Three campaign-ready angles generated from the creative direction.</p></div><button onClick={()=>{setGenerated(true);setNotice('Three new ad suggestions generated.')}}><RotateCw/> Generate more</button></div><div className="cards"><Creative image={image} n="01" title="Private access. Zero algorithms." cta="JOIN MY PAGE" onAction={()=>setNotice('Concept 01 selected for launch.')}/><Creative image={image} n="02" title="More of me. Less scrolling." cta="UNLOCK NOW" onAction={()=>setNotice('Concept 02 selected for launch.')}/><Creative image={image} n="03" title="Your invite is waiting." cta="GET ACCESS" onAction={()=>setNotice('Concept 03 selected for launch.')}/></div></div><div id="launch" className="steps"><h2>Launch readiness</h2>{['Offer and conversion objective set','Nine creative variations prepared','Audience and placements optimized','Tracking plan configured','Final campaign review'].map((x,i)=><button className={'step '+(completed.includes(i)?'done':'')} onClick={()=>setCompleted(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])} key={x}><i>{completed.includes(i)?<Check/>:i+1}</i><span>{x}<small>{i===4?'Review all campaign layers before activation.':'Completed by AI automation.'}</small></span><Check/></button>)}<button className="launch" onClick={()=>setNotice('Campaign package is ready for final review.')}><Rocket/> Review campaign</button></div></section></div>}
      </>:<WorkspaceScreen screen={active} budget={budget} setBudget={setBudget} model={model} image={image} notify={setNotice} creatorName={creatorName} setCreatorName={setCreatorName} socials={socials} setSocials={setSocials} siteUrl={siteUrl} setSiteUrl={setSiteUrl} siteState={siteState} siteData={siteData} analyzeWebsite={analyzeWebsite} selectedAsset={selectedAsset} setSelectedAsset={setSelectedAsset} go={go} setShowBilling={setShowBilling}/>} 
      {showBilling&&<BillingBoundary budget={budget} creatorName={creatorName} close={()=>setShowBilling(false)}/>} 
      {notice&&<button className="toast" onClick={()=>setNotice('')}>{notice}<span>×</span></button>}
      <footer><b>NAUGHTY PILOT</b><span>Forecasts vary with creative quality, audience, offer, tracking, seasonality, and traffic quality.</span></footer>
    </main>
  </div>
}
function Metric({icon:I,name,value}:any){return <div className="metric"><I/><span>{name}</span><b>{value}</b></div>}
function Creative({image,n,title,cta,onAction}:any){return <div className={'ad ad'+n}>{image&&<img src={image}/>}<span>CONCEPT {n}</span><h3>{title}</h3><p>Private drops. Real connection.<br/>Come a little closer.</p><button onClick={onAction}>{cta}<ArrowUpRight/></button></div>}
function WorkspaceScreen({screen,budget,setBudget,model,image,notify,creatorName,setCreatorName,socials,setSocials,siteUrl,setSiteUrl,siteState,siteData,analyzeWebsite,selectedAsset,setSelectedAsset,go,setShowBilling}:any){
  const [enabled,setEnabled]=useState<Record<string,boolean>>(()=>Object.fromEntries(channels.map(c=>[c.name,true])));
  const [campaignName,setCampaignName]=useState('Subscriber Growth Campaign');
  const toggleAll=(value:boolean)=>setEnabled(Object.fromEntries(channels.map(c=>[c.name,value])));
  const websitePanel=<section className="website-panel"><div><span>BUSINESS WEBSITE INTELLIGENCE</span><h2>Analyze business website</h2><p>Read public services, positioning, offer language, calls to action, and social links.</p></div><div className="website-form"><input type="url" value={siteUrl} placeholder="https://businesswebsite.com" onChange={e=>setSiteUrl(e.target.value)}/><button onClick={analyzeWebsite} disabled={siteState==='loading'}><Sparkles/>{siteState==='loading'?'Analyzing…':'Analyze website'}</button></div>{siteState==='loading'&&<div className="site-loader"><i/><span>Reading the live business website and extracting brand signals…</span></div>}{siteState==='error'&&<div className="site-error">Website analysis could not be completed. Check the URL and try again.</div>}{siteData&&<div className="site-result"><div><span>BUSINESS</span><b>{siteData.profile.brand}</b></div><div><span>POSITIONING</span><b>{siteData.profile.positioning}</b></div><div><span>VOICE</span><b>{siteData.profile.voice}</b></div><div><span>PRIMARY CTA</span><b>{siteData.profile.primaryCta}</b></div><div className="wide"><span>SERVICE & CONTENT SIGNALS</span><b>{siteData.headings.slice(0,5).join(' · ')}</b></div><div className="wide"><span>SOCIAL LINKS FOUND</span><b>{siteData.socialLinks.length||'None detected'}</b></div></div>}</section>;
  const adSuggestions=siteData?.adSuggestions?.length?siteData.adSuggestions:['Private access. Zero algorithms.','More of me. Less scrolling.','Your invite is waiting.','A side of me made for you.','See what never hits the feed.','Your private invite is here.'];
  const top=<div className="workspace-head"><div><span>NAUGHTY PILOT / {screen.toUpperCase()}</span><h1>{screen}</h1><p>{screen==='Chat Studio'?'Build campaign assets in conversation with your specialist agent team.':screen==='Model Assets'?'Creator-organized media ready to turn into campaigns.':screen==='Naughty Cheat Codes'?'Proprietary campaign plays that turn creator inputs into repeatable execution.':screen==='Campaign Builder'?'Configure every campaign layer before AI optimization.':screen==='Creatives'?'Review, select, and generate campaign-ready ad variations.':screen==='Traffic Mix'?'Control every paid, organic, and creator traffic source.':screen==='Forecast'?'Explore projected acquisition and revenue scenarios.':screen==='AI Skills'?'Specialized intelligence modules powering every campaign layer.':'Review every requirement before campaign activation.'}</p></div><button onClick={()=>notify(screen==='AI Skills'?'Skill library is ready.':`${screen} changes saved.`)}><Check/> {screen==='AI Skills'?'System ready':'Save changes'}</button></div>;
  if(screen==='Chat Studio')return <ChatStudio siteData={siteData} image={image} selectedAsset={selectedAsset} setSelectedAsset={setSelectedAsset} notify={notify} go={go}/>;
  if(screen==='Model Assets')return <AssetLibrary siteData={siteData} uploaded={image} selectedAsset={selectedAsset} choose={(asset:string)=>{setSelectedAsset(asset);go('Chat Studio')}} notify={notify}/>;
  if(screen==='Naughty Cheat Codes')return <div className="workspace">{top}<div className="cheat-hero"><Zap/><div><span>PRIVATE PLAYBOOK LIBRARY</span><h2>Campaign intelligence your competitors cannot copy from a template.</h2><p>Combine any play with the creator profile, approved assets, traffic sources, and live website intelligence.</p></div></div><div className="cheat-library">{cheatCodes.map(([name,description],index)=><button key={name} onClick={()=>notify(`${name} loaded into Chat Studio.`)}><span>{String(index+1).padStart(2,'0')}</span><Zap/><h2>{name}</h2><p>{description}</p><b>LOAD PLAY <ArrowUpRight/></b></button>)}</div></div>;
  if(screen==='Campaign Builder')return <div className="workspace">{top}{websitePanel}<div className="form-grid"><section><h2>Business & creator profile</h2><Field label="OnlyFans name" value={creatorName} placeholder="@creatorname" onChange={setCreatorName}/><Field label="Campaign name" value={campaignName} onChange={setCampaignName}/><label>Offer type<select><option>Premium business inquiry</option><option>OnlyFans subscription</option><option>Website booking conversion</option></select></label><label>Primary destination<select><option>Business website</option><option>OnlyFans page</option><option>Campaign landing page</option></select></label></section><section><h2>Social media</h2>{Object.entries(socials).map(([key,value])=><Field key={key} label={key==='x'?'X / Twitter':key[0].toUpperCase()+key.slice(1)} value={value as string} placeholder={`@${key}handle`} onChange={(v:string)=>setSocials({...socials,[key]:v})}/>)}</section><section><h2>Optimization</h2><label>Campaign objective<select><option>Qualified inquiries</option><option>Paid subscribers</option><option>Website conversions</option></select></label><label>Starting budget <b>${budget}</b><input type="range" min="100" max="5000" step="50" value={budget} onChange={e=>setBudget(+e.target.value)}/></label><label>Audience<select><option>AI optimized · US · 21+</option><option>Custom audience</option><option>Lookalike audience</option></select></label><button className="primary" onClick={()=>notify('Website intelligence applied to the campaign.')}><Sparkles/> Build ads from website</button></section></div></div>;
  if(screen==='Creatives')return <div className="workspace">{top}<div className="creative-toolbar"><button className="primary" onClick={()=>notify(siteData?'New ads generated from the analyzed business website.':'Analyze the business website to match its exact language.')}><Sparkles/> Generate from website</button><span>{siteData?`${siteData.profile.brand} · live website language`:'Add a website in Campaign Builder'}</span></div><div className="creative-library">{adSuggestions.map((title:string,index:number)=><Creative key={index} image={image} n={String(index+1).padStart(2,'0')} title={title} cta={siteData?.profile?.primaryCta?.toUpperCase()||'SELECT AD'} onAction={()=>notify(`Creative ${index+1} selected.`)}/>)}</div></div>;
  if(screen==='Traffic Mix')return <div className="workspace">{top}<div className="traffic-actions"><button onClick={()=>toggleAll(true)}>Enable all</button><button onClick={()=>toggleAll(false)}>Pause all</button><span>{Object.values(enabled).filter(Boolean).length} of {channels.length} sources active</span></div><div className="traffic-table"><div className="tr th"><span>Source</span><span>Buying model</span><span>Allocation</span><span>Budget</span><span>Status</span></div>{channels.map(c=><div className="tr" key={c.name}><span><i style={{background:c.color}}/><b>{c.name}</b><small>{c.note}</small></span><span>{c.model}</span><span>{c.base}%</span><span>${Math.round(budget*c.base/100)}</span><button className={'switch '+(enabled[c.name]?'on':'')} onClick={()=>setEnabled({...enabled,[c.name]:!enabled[c.name]})}><i/></button></div>)}</div></div>;
  if(screen==='Forecast')return <div className="workspace">{top}<div className="forecast-screen"><div className="forecast-big"><span>PROJECTED SUBSCRIBERS</span><strong>{model.mid}</strong><p>Planning range {model.low}–{model.high}</p></div><div className="chart"><div className="chart-bars">{[34,51,46,68,61,78,72,91,84,100].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="chart-labels"><span>Day 1</span><span>Day 30</span></div></div></div><div className="forecast-kpis"><Metric icon={CircleDollarSign} name="Starting budget" value={'$'+budget}/><Metric icon={MousePointer2} name="Estimated clicks" value={model.clicks.toLocaleString()}/><Metric icon={Eye} name="Landing visits" value={model.visits.toLocaleString()}/><Metric icon={TrendingUp} name="Projected revenue" value={'$'+model.revenue.toLocaleString()}/></div></div>;
  if(screen==='AI Skills')return <div className="workspace">{top}<div className="skills-summary"><div><span>ACTIVE INTELLIGENCE</span><strong>{skillCatalog.filter(s=>s[2]==='ACTIVE').length}</strong><small>campaign skills online</small></div><p>Each module can operate independently or combine into the complete Naughty Pilot campaign system.</p></div><div className="skill-library">{skillCatalog.map(([name,description,status],index)=><button className={'skill-card '+status.toLowerCase()} key={name} onClick={()=>notify(status==='ACTIVE'?`${name} is active and ready.`:`${name} is available as an add-on.`)}><div><Sparkles/><span>{String(index+1).padStart(2,'0')}</span></div><h2>{name}</h2><p>{description}</p><footer><b>{status}</b><ArrowUpRight/></footer></button>)}</div></div>;
  return <div className="workspace">{top}<div className="launch-screen"><section><h2>Campaign readiness</h2>{['Creator profile connected','Offer and conversion event selected','Traffic sources configured','Creative variations generated','Tracking parameters prepared','Budget and schedule confirmed'].map((x,i)=><div className="review-row" key={x}><i><Check/></i><span><b>{x}</b><small>{i<4?'Complete':'Ready for final review'}</small></span><button onClick={()=>notify(`${x} opened.`)}>Edit</button></div>)}</section><div className="launch-summary"><span>CAMPAIGN SUMMARY</span><h2>{creatorName||'Creator'} · Subscriber Growth</h2><dl><div><dt>Budget</dt><dd>${budget}</dd></div><div><dt>Objective</dt><dd>Paid subscribers</dd></div><div><dt>Sources</dt><dd>7 active</dd></div><div><dt>Creatives</dt><dd>9 variations</dd></div></dl><button className="primary" onClick={()=>setShowBilling(true)}><Rocket/> Continue to activation</button><small className="secure-note"><LockKeyhole/> Secure payment handoff · demo stops before card entry</small></div></div></div>;
}

function AssetLibrary({siteData,uploaded,selectedAsset,choose,notify}:any){
  const assets=[...(uploaded?[uploaded]:[]),...(siteData?.images||[])];
  return <div className="workspace"><div className="workspace-head"><div><span>NAUGHTY PILOT / ASSET VAULT</span><h1>Model Assets</h1><p>Every customer has a private, creator-organized library for one-click ad creation.</p></div><button onClick={()=>notify('Asset upload opens from the Overview drop zone.')}><Plus/> Add assets</button></div><section className="model-collection"><div className="collection-head"><div className="model-avatar">{assets[0]?<img src={assets[0]}/>:<Users/>}</div><div><span>CREATOR COLLECTION</span><h2>{siteData?.profile?.brand||'New creator'}</h2><p>{assets.length} approved campaign assets · website and uploads</p></div><b>{assets.length?'READY':'ADD MEDIA'}</b></div>{assets.length?<div className="asset-grid">{assets.map((asset:string,index:number)=><button className={selectedAsset===asset?'selected':''} onClick={()=>choose(asset)} key={asset+index}><img src={asset} alt={`Campaign asset ${index+1}`} onError={e=>(e.currentTarget.parentElement!.style.display='none')}/><span><Plus/> CREATE IN CHAT</span></button>)}</div>:<div className="asset-empty"><ImageIcon/><h2>No campaign media yet</h2><p>Upload a photo or analyze the customer’s website to build this collection.</p></div>}</section></div>
}

function ChatStudio({siteData,image,selectedAsset,setSelectedAsset,notify,go}:any){
  const [plusOpen,setPlusOpen]=useState(false); const [panel,setPanel]=useState(''); const [running,setRunning]=useState(false); const [done,setDone]=useState(false); const [prompt,setPrompt]=useState('Build a complete conversion campaign from this creator asset.');
  const asset=selectedAsset||image||siteData?.images?.[0]; const brand=siteData?.profile?.brand||'Your creator'; const hook=siteData?.adSuggestions?.[0]||'Private access. Zero algorithms.';
  const run=()=>{setRunning(true);setDone(false);setPlusOpen(false);setTimeout(()=>{setRunning(false);setDone(true)},1200)};
  const selectPanel=(name:string)=>{setPanel(name);setPlusOpen(false)};
  return <div className="chat-workspace"><section className="chat-main"><div className="chat-brand"><img src="/naughty-pilot-logo.png"/><div><span>NAUGHTY PILOT COMMAND</span><h1>What are we building today?</h1></div></div><div className="messages"><div className="agent-message"><div className="bot-mark"><Bot/></div><div><b>Naughty Pilot</b><p>I can use the website profile, creator assets, traffic intelligence, and specialist skills to build the campaign in one pass.</p></div></div>{asset&&<div className="user-message"><img src={asset}/><div><b>Selected creator asset</b><p>{prompt}</p></div></div>}{running&&<div className="agent-message working"><div className="bot-mark"><Sparkles/></div><div><b>Campaign crew is working</b><p>Brand Strategist → Creative Director → Media Buyer → Compliance Review</p><i/></div></div>}{done&&<div className="agent-message result-message"><div className="bot-mark"><Check/></div><div><b>Campaign package ready</b><h2>{hook}</h2><p>9 creative variations · 7-source traffic plan · $300 test allocation · tracking and launch checklist prepared.</p><div className="result-actions"><button onClick={()=>go('Creatives')}>View ads</button><button onClick={()=>go('Launch Plan')}>Review launch</button></div></div></div>}</div><div className="composer"><button className="plus" onClick={()=>setPlusOpen(!plusOpen)} aria-label="Open tools"><Plus/></button>{plusOpen&&<div className="plus-menu"><button onClick={()=>selectPanel('Skills')}><Sparkles/><span><b>Skills</b><small>Campaign capabilities</small></span></button><button onClick={()=>selectPanel('Agents')}><Bot/><span><b>Agents</b><small>Specialist campaign crew</small></span></button><button onClick={()=>selectPanel('Naughty Cheat Codes')}><Zap/><span><b>Naughty Cheat Codes</b><small>Private playbook library</small></span></button><button onClick={()=>go('Model Assets')}><ImageIcon/><span><b>Model Assets</b><small>Choose creator media</small></span></button></div>}<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} /><button className="send" onClick={run} disabled={running}><Send/></button></div><small className="chat-foot">Campaign suggestions require human review before activation.</small></section><aside className="chat-side"><div><span>ACTIVE CUSTOMER</span><h2>{brand}</h2><p>{siteData?'Website intelligence connected':'Add a website in Campaign Builder'}</p></div>{asset?<img className="selected-preview" src={asset}/>:<button className="empty-preview" onClick={()=>go('Model Assets')}><ImageIcon/>Choose creator asset</button>}<div className="crew"><span>CAMPAIGN CREW</span>{['Brand Strategist','Creative Director','Media Buyer','Compliance Reviewer'].map(name=><div key={name}><i/><b>{name}</b><small>ONLINE</small></div>)}</div></aside>{panel&&<Drawer title={panel} close={()=>setPanel('')} notify={notify}/>}</div>
}

function Drawer({title,close,notify}:any){
  const items=title==='Skills'?skillCatalog.slice(0,8).map(x=>[x[0],x[1]]):title==='Agents'?[['Brand Strategist','Positioning, voice, and offer alignment'],['Creative Director','Hooks, formats, copy, and variations'],['Media Buyer','Source mix, allocation, and optimization'],['Compliance Reviewer','18+, consent, policy, and claim checks'],['Website Analyst','Live public-site brand intelligence']]:cheatCodes;
  return <div className="drawer"><div className="drawer-head"><div><span>ADD TO CHAT</span><h2>{title}</h2></div><button onClick={close}><X/></button></div><div className="drawer-list">{items.map(([name,description]:any)=><button key={name} onClick={()=>{notify(`${name} added to Chat Studio.`);close()}}><div>{title==='Agents'?<Bot/>:title==='Skills'?<Sparkles/>:<Zap/>}</div><span><b>{name}</b><small>{description}</small></span><Plus/></button>)}</div></div>
}

function BillingBoundary({budget,creatorName,close}:any){return <div className="billing-overlay"><div className="billing-modal"><button className="modal-close" onClick={close}><X/></button><div className="billing-lock"><LockKeyhole/></div><span>SECURE ACTIVATION HANDOFF</span><h1>Campaign is ready to fund.</h1><p>The complete demo ends here. A production account would continue to a PCI-compliant payment provider; Naughty Pilot does not collect card details on this screen.</p><div className="billing-summary"><div><span>Campaign</span><b>{creatorName||'Creator'} · Subscriber Growth</b></div><div><span>Test media budget</span><b>${budget}.00</b></div><div><span>Activation status</span><b>Ready</b></div></div><button className="payment-boundary" onClick={()=>{}}><CreditCard/> Add payment method <ArrowUpRight/></button><small><ShieldCheck/> DEMO STOP POINT · No charge made · No card data collected</small></div></div>}
function Field({label,value,placeholder,onChange}:any){return <label>{label}<input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
createRoot(document.getElementById('root')!).render(<App/>);
